#pragma once

#ifndef CV_DYNAMIC_DIPLO_MANAGER_H
#define CV_DYNAMIC_DIPLO_MANAGER_H

#include <vector>
#include <hash_map>
#include "CvEnums.h"
#include "CvStructs.h"

class CvDynamicDiploManager
{
	friend class CvGame; // XANA (note): Only the CvGame class needs to initialize or reset this dynamic response manager to default values. No need for other classes to have the same level of access!
public:
	static CvDynamicDiploManager& getInstance(); // XANA (note): WinINet - access for writing AND reading permissions!
	static CvDynamicDiploManager const& getConstInstance() { return getInstance(); } // XANA (note): main game thread - acccess for reading permissions ONLY!

	// Called by WinINet thread to safely drop responses into data containers
	/* XANA (warning):
	DO NOT USE FIRAXIS GLOBAL FUNCTIONS OR ASSERTIONS IN THIS FUNCTION
	THIS OPERATION WILL BE CALLED VIA A BACKGROUND THREAD
	ATTEMPTING TO DO SO WILL CRASH THE GAME */
	void updateAIPlayerAvailableResponses(LLMResultData const& kResult);
	
	// Called by main game thread to assign response objects to LLM prompt structures
	int getAvailableResponseGroupID(PlayerTypes eAIPlayer, DiploCommentTypes eComment) const;

	// Called by Python/CvDiplomacy to fetch data for the local UI
	int getNumResponses(PlayerTypes eAIPlayer, DiploCommentTypes eComment) const;
	bool isResponseForCivilization(PlayerTypes eAIPlayer, DiploCommentTypes eComment, int iGroupIndex) const;
	bool isResponseForLeaderHead(PlayerTypes eAIPlayer, DiploCommentTypes eComment, int iGroupIndex) const;
	bool isResponseForAttitude(PlayerTypes eAIPlayer, PlayerTypes eOtherPlayer, DiploCommentTypes eComment, int iGroupIndex) const;
	bool isResponseForDiplomacyPower(PlayerTypes eAIPlayer, PlayerTypes eOtherPlayer, DiploCommentTypes eComment, int iGroupIndex) const;
	int getNumDiplomacyText(PlayerTypes eAIPlayer, DiploCommentTypes eComment, int iGroupIndex) const;
	const char* getDiplomacyText(PlayerTypes eAIPlayer, DiploCommentTypes eComment, int iGroupIndex, int iVariant) const;

private:
	// Static lightweight unique class - no creation, no copying, no assignment, no deletion
	CvDynamicDiploManager() {};
	~CvDynamicDiploManager() {};
	CvDynamicDiploManager(CvDynamicDiploManager const& kOther);
	CvDynamicDiploManager& operator=(CvDynamicDiploManager const& kOther);
	
	void init();
	void reset();
	void uninit();
	
	CvCriticalSection m_CS;
	
	stdext::hash_map<int /* PlayerTypes */, std::vector<DynamicResponse*> > m_LLMDiploResponses; // not serialized into save game because responses are generated by LLM prompts
	bool m_bInitialized;
	int m_iNumDiploCommentTypes;
	
	void setInitialItems();
	void clearResponses(PlayerTypes eAIPlayer);
	bool getCivilizationTypes(PlayerTypes eAIPlayer, DiploCommentTypes eComment, CivilizationTypes eCiv, int iGroupIndex) const;
	bool getLeaderHeadTypes(PlayerTypes eAIPlayer, DiploCommentTypes eComment, LeaderHeadTypes eLeader, int iGroupIndex) const;
	bool getAttitudeTypes(PlayerTypes eAIPlayer, DiploCommentTypes eComment, AttitudeTypes eAttitude, int iGroupIndex const;
	bool getDiplomacyPowerTypes(PlayerTypes eAIPlayer, DiploCommentTypes eComment, DiplomacyPowerTypes ePower, int iGroupIndex) const;
};

#define DIPLOMGR CvDynamicDiploManager::getConstInstance() // XANA (note): Game thread will be mostly reading from this class, mark it const for safety!

#endif